# Generated by Django 4.2.11 on 2024-04-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='authname',
            field=models.CharField(max_length=25),
        ),
    ]
