# Generated by Django 4.2.11 on 2024-04-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_blogs_authname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
